config/routes.rb
Rails.application.routes.draw do
  get 'home/welcome'

  get 'home/find_workers'

  get 'edit_profile/:id' => 'home#edit_profile', as: :edit_profile
  put 'edit_profile/:id' => 'home#update_profile'

  resources :profession_types
  resources :professions
  devise_for :users

  root 'home#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < User
end

app/models/profession.rb
class Profession < ApplicationRecord

  has_many :worker_profession, dependent: :destroy
  has_many :worker, through: :worker_profession
  belongs_to :profession_type

  validates :name, presence: true, length: {in: 2..100}
  validates :profession_type, presence: true

  delegate :title, to: :profession_type, prefix: true
end

app/models/profession_type.rb
class ProfessionType < ApplicationRecord

  has_many :professions, dependent: :destroy

  validates :title, presence: true, length: { in: 2..50 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :email, presence: true
  validates :firstname, presence: true, length: {in: 2..100}
  validates :lastname, length: {in: 2..100}
end

app/models/worker.rb
class Worker < User

  has_many :worker_profession, dependent: :destroy
  has_many :professions, through: :worker_profession

  validates :professions, presence: true, on: :update

  scope :with_professions, -> (professions){joins(:professions).where(professions: {id: professions}).distinct}
end

app/models/worker_profession.rb
class WorkerProfession < ApplicationRecord
  belongs_to :worker
  belongs_to :profession
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :type])
  end

  def authenticate_admin!
    authenticate_user!
    redirect_to root_path unless current_user.type == 'Admin'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end

  def find_workers
    @workers = Worker.with_professions(search_params)
  end

  def edit_profile
    @user = User.find(params[:id])
  end

  def update_profile
    @user = User.find(params[:id])
    if @user.update(worker_params)
      flash[:success] = 'Your profile has been successfully updated !'
      redirect_to edit_profile_path
    else
      render :edit_profile
    end
  end

  private

  def search_params
    params[:profession_ids].nil? ? Profession.all.pluck(:id) : params[:profession_ids]
  end

  def worker_params
    return params.require(:worker).permit(:firstname, :lastname, :email, profession_ids: []) if params.include?(:worker)
    return params.require(:customer).permit(:firstname, :lastname, :email, profession_ids: []) if params.include?(:customer)
    return params.require(:admin).permit(:firstname, :lastname, :email, profession_ids: []) if params.include?(:admin)
  end
end

app/controllers/profession_types_controller.rb
class ProfessionTypesController < ApplicationController
  before_action :set_profession_type, only: [:show, :edit, :update, :destroy]

  def index
    @profession_types = ProfessionType.all
  end

  def show
  end

  def new
    @profession_type = ProfessionType.new
  end

  def edit
  end

  def create
    @profession_type = ProfessionType.new(profession_type_params)

    respond_to do |format|
      if @profession_type.save
        format.html { redirect_to @profession_type, notice: 'Profession type was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @profession_type.update(profession_type_params)
        format.html { redirect_to @profession_type, notice: 'Profession type was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @profession_type.destroy
    respond_to do |format|
      format.html { redirect_to profession_types_url, notice: 'Profession type was successfully destroyed.' }
    end
  end

  private
    def set_profession_type
      @profession_type = ProfessionType.find(params[:id])
    end

    def profession_type_params
      params.require(:profession_type).permit(:title)
    end
end

app/controllers/professions_controller.rb
class ProfessionsController < ApplicationController
  before_action :set_profession, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  def index
    @professions = Profession.all
  end

  def show
  end

  def new
    @profession = Profession.new
  end

  def edit
  end

  def create
    @profession = Profession.new(profession_params)

    respond_to do |format|
      if @profession.save
        format.html { redirect_to @profession, notice: 'Profession was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @profession.update(profession_params)
        format.html { redirect_to @profession, notice: 'Profession was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @profession.destroy
    respond_to do |format|
      format.html { redirect_to professions_url, notice: 'Profession was successfully destroyed.' }
    end
  end

  private
    def set_profession
      @profession = Profession.find(params[:id])
    end

    def profession_params
      params.require(:profession).permit(:name, :profession_type_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def worker_signed_in?
    current_user.type == 'Worker'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profession_types_helper.rb
module ProfessionTypesHelper
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/views/home/edit_profile.html.haml
%h2 Edit Profile
= simple_form_for(@user, url: edit_profile_path(@user), html: { method: :put }) do |f|
  = f.error_notification
  .form-inputs
    = f.input :firstname, required: true, autofocus: true
    = f.input :lastname, required: true, autofocus: true
    = f.input :email, required: true, autofocus: true
    - if @user.type == 'Worker'
      = f.association :professions
  .form-actions
    = f.button :submit, "Update"

app/views/home/find_workers.html.haml
= form_tag home_find_workers_path, method: :get do |f|
  = select_tag :profession_ids, options_from_collection_for_select(Profession.all, :id, :name), multiple: true, class: 'select2'
  = submit_tag 'Search', class: 'btn'

%h2.text-left Workers

.table-responsive.clearfix
  %table.table.table-bordered
    %thead
      %tr
        %th Firstname
        %th Lastname
        %th Email
        %th Professions

    %tbody
      - @workers.each do |worker|
        %tr
          %td= worker.firstname
          %td= worker.lastname
          %td= worker.email
          %td= worker.professions.pluck(:name).join(', ')

app/views/home/welcome.html.haml
%h1 Home#welcome
%p Find me in app/views/home/welcome.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ProfessionalsSearch
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/header'
    = render 'shared/flashes'
    = yield

app/views/profession_types/_form.html.haml
= form_for @profession_type do |f|
  - if @profession_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profession_type.errors.count, "error")} prohibited this profession_type from being saved:"
      %ul
        - @profession_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/profession_types/edit.html.haml
%h1 Editing profession_type

= render 'form'

= link_to 'Show', @profession_type
\|
= link_to 'Back', profession_types_path

app/views/profession_types/index.html.haml
%h1 Listing profession_types

%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @profession_types.each do |profession_type|
      %tr
        %td= profession_type.title
        %td= link_to 'Show', profession_type
        %td= link_to 'Edit', edit_profession_type_path(profession_type)
        %td= link_to 'Destroy', profession_type, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profession type', new_profession_type_path

app/views/profession_types/new.html.haml
%h1 New profession_type

= render 'form'

= link_to 'Back', profession_types_path

app/views/profession_types/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @profession_type.title

= link_to 'Edit', edit_profession_type_path(@profession_type)
\|
= link_to 'Back', profession_types_path

app/views/professions/_form.html.haml
= form_for @profession do |f|
  - if @profession.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profession.errors.count, "error")} prohibited this profession from being saved:"
      %ul
        - @profession.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :profession_type
    = f.collection_select :profession_type_id, ProfessionType.all, :id, :title
  .actions
    = f.submit 'Save'

app/views/professions/edit.html.haml
%h1 Editing profession

= render 'form'

= link_to 'Show', @profession
\|
= link_to 'Back', professions_path

app/views/professions/index.html.haml
%h1 Listing professions

%table
  %thead
    %tr
      %th Name
      %th Profession type
      %th
      %th
      %th

  %tbody
    - @professions.each do |profession|
      %tr
        %td= profession.name
        %td= profession.profession_type_title
        %td= link_to 'Show', profession
        %td= link_to 'Edit', edit_profession_path(profession)
        %td= link_to 'Destroy', profession, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profession', new_profession_path

app/views/professions/new.html.haml
%h1 New profession

= render 'form'

= link_to 'Back', professions_path

app/views/professions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @profession.name
%p
  %b Profession type:
  = @profession.profession_type_title

= link_to 'Edit', edit_profession_path(@profession)
\|
= link_to 'Back', professions_path

app/views/shared/_flashes.html.haml
/ Possible flash message types:
/ - success
/ - error
/ - warning
/ - info

- flash.to_a.to_h.each do |key, value|
  - next if value.nil?
  :ruby
    case key
      when "success"
        style_class = "alert-success"
        icon_class = "fa-check"
      when "error", "alert"
        style_class = "alert-danger"
        icon_class = "fa-exclamation-triangle"
      when "warning"
        style_class = "alert-warning"
        icon_class = "fa-exclamation-triangle"
      when "info"
        style_class = "alert-info"
        icon_class = "fa-info-circle"
      else
        style_class = "alert-info"
        icon_class = "fa-info-circle"
    end

  .alert.alert-block{class: style_class}
    %button.close{"data-dismiss" => "alert"}
      %i.ace-icon.fa.fa-times

    %i.ace-icon.fa{class: icon_class}
    = raw(value)

- flash.clear

app/views/shared/_header.html.haml
%header
  / Static navbar
  %nav.navbar.navbar-default.navbar-static-top
    .container
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "#"} Search Professionals
      #navbar.navbar-collapse.collapse.pull-right
        %ul.nav.navbar-nav
          - if user_signed_in?
            %li.active
              %a{:href => "/"} Home
            %li
              = link_to('Edit Profile', edit_profile_path(current_user), :method => :get)
            %li
              = link_to('Search Workers', home_find_workers_path)
            %li
              = link_to('Logout', destroy_user_session_path, :method => :delete)
          - else
            %li
              = link_to('Search Workers', home_find_workers_path)
            %li
              = link_to('Login', new_user_session_path)
      / /.nav-collapse